:sectnums:
:sectnumlevels: 3
:markup-in-source: verbatim,attributes,quotes
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:disk0: /dev/vda
:disk1: /dev/vdb
:disk2: /dev/vdc
:disk3: /dev/vdd
:disk4: /dev/vde
:disk_glob: /dev/vd{b..e}
:format_cmd_exec: source,options="nowrap",subs="{markup-in-source}",role="copy"
:format_cmd_output: bash,options="nowrap",subs="{markup-in-source}"
ifeval::["%cloud_provider%" == "ec2"]
:disk0: /dev/nvme0n1
:disk1: /dev/nvme1n1
:disk2: /dev/nvme2n1
:disk3: /dev/nvme3n1
:disk4: /dev/nvme4n1
:disk_glob: /dev/nvme{1..4}n1
:format_cmd_exec: source,options="nowrap",subs="{markup-in-source}",role="execute"
endif::[]



= Intermediate: *Storage Management* (stratis)

== Overview

== Getting Started

For these exercises, you will be using the host `node2` as user `root`.

From host `bastion`, ssh to `node2`.

[{format_cmd_exec}]
----
ssh node2
----

Use `sudo` to elevate your privileges.

[{format_cmd_exec}]
----
[[ "$UID" == 0 ]] || sudo -i
----

Verify that you are on the right host for these exercises.

[{format_cmd_exec}]
----
workshop-stratis-checkhost.sh
----

You are now ready to proceed with these exercises.

== Grow Storage Pool

Stratis also makes it easy to add space to a pool.  Suppose the “summitfs” filesystem is growing close to the physical space in “summitpool”.  Adding an additional disk/block device is done using:

[{format_cmd_exec}]
----
stratis pool add-data summitpool {disk3}
----

[{format_cmd_exec}]
----
stratis blockdev
----

[{format_cmd_output}]
----
Pool Name    Device Node    Physical Size   Tier
summitpool   {disk1}                5 GiB   Data
summitpool   {disk2}                5 GiB   Data
summitpool   {disk3}                5 GiB   Data
----

Verify that the pool shows the additional space, and that the amount used is now in a safe range.

[{format_cmd_exec}]
----
stratis pool
----

[{format_cmd_output}]
----
Name                          Total Physical   Properties          UUID
summitpool   15 GiB / 590.65 MiB / 14.42 GiB      ~Ca,~Cr   4b86ce9b...
----

== Add Cache Device

Stratis also makes it easy to add cache devices.  For example, say the filesystem we just created runs into some I/O performance issues.  You bought an SSD (solid state disk) and need to configure it into the system to act as a high speed cache.  Use the following commands to add the drive {disk4} and check its status:

[{format_cmd_exec}]
----
stratis pool init-cache summitpool  {disk4}
----

[{format_cmd_exec}]
----
stratis blockdev
----

[{format_cmd_output}]
----
Pool Name    Device Node    Physical Size   Tier
summitpool   {disk1}                5 GiB   Data
summitpool   {disk2}                5 GiB   Data
summitpool   {disk3}                5 GiB   Data
summitpool   {disk4}                5 GiB  Cache
----



== Conclusion

This concludes the exercises related to stratis.

Time to finish this unit and return the shell to it's home position.

[{format_cmd_exec}]
----
workshop-finish-exercise.sh
----



== Additional Resources

Red Hat Documentation

This lab does not get into more advanced topics like encryption or snapshots.  For more information on these and more details on Stratis in general, see the official Red Hat documentation here:

    * link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/managing_file_systems/setting-up-stratis-file-systems_managing-file-systems[Managing Filesystems: Chapter 39. Setting Up Stratis File Systems]

[discrete]
== End of Unit

ifdef::env-github[]
link:../RHEL9-Workshop.adoc#toc[Return to TOC]
endif::[]

////
Always end files with a blank line to avoid include problems.
Verifide for RHEL92
////


