
= *Trouble Shooting* (man,info,journald,syslog)

[discrete]
== *Skill Level: Fundamental*




== Overview

There are 2 primary ways to get help in RHEL

    * man pages
    * info pages

Likewise, there are 2 primary native solutions for logging

    * journald
    * syslog

In this unit we'll explore the basics of seeking for help and troubleshooting issues.

== Getting Started

For these exercises, you will be using the host `node1` as user `root`.

From host `bastion`, ssh to `node1`.

[{format_cmd}]
----
ssh node1
----

Use `sudo` to elevate your privileges.

[{format_cmd}]
----
[[ "$UID" == 0 ]] || sudo -i
----

Verify that you are on the right host for these exercises.

[{format_cmd}]
----
workshop-man-checkhost.sh
----

You are now ready to proceed with these exercises.

== Core Concepts

*Man* pages (short for manual pages) are a form of online software documentation which covers the use 
and implementation of tools on UNIX and UNIX-like platform (ie: Linux).  Topics covered include:

  * programs
  * configuration files
  * system libraries
  * system calls
  * more

*Info* pages on the other hand are another system of online documentation developed and maintained by 
the GNU project, also for UNIX and UNIX-like platforms.  

The difference is that *man* pages are singular in nature, where-as *info* pages are hypertext and linked
to one another there-by making navigation of the material very interactive.  

NOTE: This is probably not a fair and thorough distinction of man vs. info. Please let us know
if you have a more appropriate statement.

== Manual Pages (man)

=== Show page

Man is traditionally invoked with a single operand, your subject.

Let's begin by looking up the man page for *man* itself.

[{format_cmd}]
----
man man
----

The respose is a "paged" document (ie: you get 1 page at a time, you hit spacebar to get the next page).
The response is also divided into sections:

  * NAME
  * SYNOPSIS
  * DESCRIPTION
  * OPTIONS
  * EXAMPLES
  * sometimes more or less...

But in our case, let's look more carefully are the output

[{format_output}]
----
....<snip>

The table below shows the section numbers of the manual followed by the types of pages they contain.

1   Executable programs or shell commands
2   System calls (functions provided by the kernel)
3   Library calls (functions within program libraries)
4   Special files (usually found in /dev)
5   File formats and conventions eg /etc/passwd
6   Games
7   Miscellaneous (including macro packages and conventions), e.g. man(7), groff(7)
8   System administration commands (usually only for root)
9   Kernel routines [Non standard]

A manual page consists of several sections.

Conventional  section  names include NAME, SYNOPSIS, CONFIGURATION, DESCRIPTION, OPTIONS, EXIT STATUS, RETURN VALUE, ERRORS, ENVIRONMENT, FILES, VERSIONS, CONFORMING TO,
NOTES, BUGS, EXAMPLE, AUTHORS, and SEE ALSO.

....<snip>
----

Notice the table of "section numbers".  More on that laster, but just make note that manuals pages are structured into categories.  Sometimes when the search is ambiguous, you may need to specify which section of the pages you want to search.

=== Locate page

Moving on, let's look at a page for the command *ssh*.

[{format_cmd}]
----
man ssh
----

[{format_output}]
----
NAME
     ssh — OpenSSH SSH client (remote login program)

SYNOPSIS
     ssh [-46AaCfGgKkMNnqsTtVvXxYy] [-B bind_interface] [-b bind_address] [-c cipher_spec] [-D [bind_address:]port] [-E log_file] [-e escape_char] [-F configfile] [-I pkcs11]
         [-i identity_file] [-J destination] [-L address] [-l login_name] [-m mac_spec] [-O ctl_cmd] [-o option] [-p port] [-Q query_option] [-R address] [-S ctl_path]
         [-W host:port] [-w local_tun[:remote_tun]] destination [command]
----

And there you have it, complete information on how to invoke ssh with all of it's required and optional parameters.

=== Search for key words

=== Locate page for config file

== Information Pages (info)

=== Show page

=== Locate page

=== Search for key words

=== Locate page for config file

== Further Reading

[discrete]
== End of Unit

////
Always end files with a blank line to avoid include problems.
////

