
= *Container Development* (buildah & skopeo)

[discrete]
== *Skill Level: Intermediate* icon:check[]




== Overview

NOTE: These exercises are an extension of the `podman` unit and although not required, it is strongly encourage that you complete that unit first.

In this unit, we will continue to work with containers and get familiar with `Buildah` and `Skopeo`.  

== Getting Started

For these exercises, you will be using the host `node3` as user `root`.

From host `bastion`, ssh to `node3`.

[{format_cmd}]
----
ssh node3
----

Use `sudo` to elevate your privileges.

[{format_cmd}]
----
[[ "$UID" == 0 ]] || sudo -i
----

Verify that you are on the right host for these exercises.

[{format_cmd}]
----
workshop-buildah-checkhost.sh
----

You are now ready to proceed with these exercises.

== Create a Container Image With Buildah

In the previous lab on `podman`, we pulled down the ubi image and used an OCIFile to build a "webserver" container image. That process used `buildah` under the hood, but in this lab we are going to use `buildah` directly to create a similar image manually, step by step.

=== Start a Fresh Build

Let's get started by creating a new working container based off of the ubi image.

[{format_cmd}]
----
buildah from registry.access.redhat.com/ubi10-beta/ubi:latest
----

[{format_output}]
----
Trying to pull registry.access.redhat.com/ubi10-beta/ubi:latest...
Getting image source signatures
Checking if image destination supports signatures
Copying blob 9dcf0326ccda done   | 
Copying blob bd69bf9256bd done   | 
Copying config 8ba11fcef4 done   | 
Writing manifest to image destination
Storing signatures
ubi-working-container
----

This gives us the name of the "working container" and it is this container image that we will modify with buildah.

=== Add a Custom File

Let's run:

[{format_cmd}]
----
buildah copy ubi-working-container /var/tmp/buildah-dan-cries.txt /var/www/html/dan-cries.txt
----

[{format_output}]
----
34f1621a22ffd90a2ebbd58eba315089dc2704ac69a3d33d60362422e4ec26a1
----

At this point, you have copied your local `dan-cries.txt` into the the ubi-working-container image.

The steps you performed above is equivalent to the following OCIFile (or Dockerfile):

[{format_output}]
----
FROM ubi10-beta/ubi
COPY /root/dan-cries.txt /var/www/html/
----

So it's nice that we can do that with buildah, manually.

But wait there's more!!!

=== Install Additional Packages

We need to install an httpd server in our image, and what better way to do that than a simple `dnf install`.

[{format_cmd}]
----
buildah run ubi-working-container dnf install -y httpd
----

[{format_output}]
----
...<output truncated>...

Installed:
  apr-1.7.5-2.el10.x86_64                           apr-util-1.6.3-21.el10.x86_64                     
  apr-util-lmdb-1.6.3-21.el10.x86_64                apr-util-openssl-1.6.3-21.el10.x86_64             
  httpd-2.4.63-1.el10.x86_64                        httpd-core-2.4.63-1.el10.x86_64                   
  httpd-filesystem-2.4.63-1.el10.noarch             httpd-tools-2.4.63-1.el10.x86_64                  
  libbrotli-1.1.0-6.el10.x86_64                     lmdb-libs-0.9.32-4.el10.x86_64                    
  mailcap-2.1.54-8.el10.noarch                      mod_http2-2.0.29-2.el10.x86_64                    
  mod_lua-2.4.63-1.el10.x86_64                      redhat-logos-httpd-100.0-2.el10.noarch            

Complete!
----

=== Configure the Entry Point

Next we set the entry point (command) so when the image deploys it knows what process to launch.

[{format_cmd}]
----
buildah config --cmd "/usr/sbin/httpd -D FOREGROUND" ubi-working-container
----

=== Validate the Container Image

Now let us take a peek at our image and validate some of our changes.

Proceed to mount the root filesystem of your container with:

[{format_cmd}]
----
buildah mount ubi-working-container
----

[{format_output}]
----
/var/lib/containers/storage/overlay/3456a159b5b3c9e3056d14b97bde1f0e770500dd1cdd6168c894a52a3b3f12ee/merged
----

Using the long path provided by your mount command, change directories.

[{format_cmd}]
----
cd $( buildah mount ubi-working-container )
----

[{format_cmd}]
----
ls -lah ./var/www/html
----

[{format_output}]
----
total 16K
drwxr-xr-x. 2 root root 4.0K Apr 12 21:12 .
drwxr-xr-x. 3 root root 4.0K Apr 12 21:12 ..
-rw-r--r--. 1 root root   58 Apr 12 21:12 dan-cries.txt
----

There is our `dan-cries.txt`! Let's add an additional file:

[{format_cmd}]
----
cp /var/tmp/buildah-index.html ./var/www/html/index.html
----

[{format_cmd}]
----
cat ./var/www/html/index.html
----

[{format_output}]
----
<html>
<title>Stop Disabling SELinux</title>
<body>
<p>
Seriously, stop disabling SELinux. Learn how to use it before you blindly shut it off.
</p>
</body>
</html>
----

Let us just double check contents of the httpd docroot one last time:

[{format_cmd}]
----
ls -lahZ ./var/www/html/
----

[{format_output}]
----
total 20K
drwxr-xr-x. 2 root root system_u:object_r:container_file_t:s0:c60,c544 4.0K Apr 12 21:25 .
drwxr-xr-x. 3 root root system_u:object_r:container_file_t:s0:c60,c544 4.0K Apr 12 21:12 ..
-rw-r--r--. 1 root root system_u:object_r:container_file_t:s0:c60,c544   58 Apr 12 21:12 dan-cries.txt
-rw-r--r--. 1 root root system_u:object_r:container_file_t:s0:c60,c544  164 Apr 12 21:24 index.html
----

When you are done making direct changes to the root filesystem of your container, you can run:

[{format_cmd}]
----
cd /root
buildah unmount ubi-working-container
----

[{format_output}]
----
e918debcaabb5820997b1a4969fbd45284adc0a2869d1f22a1bce78f703ff3c6
----

==== Commit Changes to New Image

At this point, we've used buildah to run commands and create a container image similar to those in the OCIFile used in the `podman` unit.  Go ahead and commit the working container in to an actual container image:

[{format_cmd}]
----
buildah commit ubi-working-container webserver2
----

[{format_output}]
----
Getting image source signatures
Copying blob d3ada5af5602 skipped: already exists
Copying blob 668db11eda93 skipped: already exists
Copying blob 0f75b7e04ec6 done
Copying config a831badcea done
Writing manifest to image destination
Storing signatures
a831badcea41e924fd4a37f98431702142c17a64d06bd5444ac4471c1285be50
----

Let's look at our images:

[{format_cmd}]
----
podman images
----

[{format_output}]
----
REPOSITORY                                 TAG         IMAGE ID      CREATED        SIZE
localhost/webserver2                       latest      eb03c25f4be6  6 seconds ago  263 MB
registry.access.redhat.com/ubi9/ubi        latest      18ac20acd5ec  3 days ago     217 MB
registry.access.redhat.com/ubi10-beta/ubi  latest      8ba11fcef4ef  7 weeks ago    212 MB
----

==== Deploy

Now let's run that webserver:

[{format_cmd}]
----
podman run -d -p 8080:80 webserver2
----

==== Validate

Finally let's test our new webserver:

[{format_cmd}]
----
curl http://localhost:8080/
----

[{format_output}]
----
<html>
<title>Stop Disabling SELinux</title>
<body>
<p>
Seriously, stop disabling SELinux. Learn how to use it before you blindly shut it off.
</p>
</body>
</html>
----

and:

[{format_cmd}]
----
curl http://localhost:8080/dan-cries.txt
----

[{format_output}]
----
Every time you run setenforce 0, you make Dan Walsh weep.
----

As you can see, all of the changes we made with buildah are active and working in this new container image!

== Inspecting Images with Skopeo

Let's take a look at the webserver2:latest container that we just built:

[{format_cmd}]
----
skopeo inspect containers-storage:localhost/webserver2:latest
----

[{format_output}]
----
INFO[0000] Not using native diff for overlay, this may cause degraded performance for building images: 
kernel has CONFIG_OVERLAY_FS_REDIRECT_DIR enabled 
{         
    "Name": "localhost/webserver2",
    "Digest": "sha256:c4f8e1767e680c7eebdd4cbf55f0a91dd0e562ae6355acf642d012ee6cd863a4",
    "RepoTags": [],                                                                                    
    "Created": "2025-05-01T23:22:31.483299826Z",
    "DockerVersion": "",                           
    "Labels": {
        "architecture": "x86_64",
        "build-date": "2025-03-11T07:01:34",                                                           
        "com.redhat.component": "ubi10-container",                                                     
        "com.redhat.license_terms": "https://www.redhat.com/en/about/red-hat-end-user-license-agreement
s#UBI",                                            
        "description": "The Universal Base Image is designed and engineered to be the base layer for al
l of your containerized applications, middleware and utilities. This base image is freely redistributab
le, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. This ima
ge is maintained by Red Hat and updated regularly.",                        
        "distribution-scope": "public",
        "io.buildah.version": "1.39.0",
        "io.k8s.description": "The Universal Base Image is designed and engineered to be the base layer
 for all of your containerized applications, middleware and utilities. This base image is freely redist
ributable, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. T
his image is maintained by Red Hat and updated regularly.",
        "io.k8s.display-name": "Red Hat Universal Base Image 10",
        "io.openshift.expose-services": "",
        "io.openshift.tags": "base rhel10",
        "maintainer": "Red Hat, Inc.",
        "name": "ubi10",
        "release": "1741674993",
        "summary": "Provides the latest release of Red Hat Universal Base Image 10.",
        "url": "https://www.redhat.com",
        "vcs-ref": "eedd49665e8d30810907cf4ebb351ff15ebb8735",
        "vcs-type": "git",
        "vendor": "Red Hat, Inc.",
        "version": "10.0-beta"
    },
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:e3b16f523d9f9d4dec8a471ce071a36fa78618f1420a881ff4aa8a96f4df9f40",
        "sha256:320cd1d2c7387a0cec459e66e5fbfb2d103cf56ac4b3dcc4c48c5a184a933096",
        "sha256:508be23c840e6e212e93d131cf85640a3b65810bd7037176ddad8070423f7cf3"
    ],
    "LayersData": [
        {
            "MIMEType": "application/vnd.oci.image.layer.v1.tar",
            "Digest": "sha256:e3b16f523d9f9d4dec8a471ce071a36fa78618f1420a881ff4aa8a96f4df9f40",
            "Size": 211851264,
            "Annotations": null
        },
        {
            "MIMEType": "application/vnd.oci.image.layer.v1.tar",
            "Digest": "sha256:320cd1d2c7387a0cec459e66e5fbfb2d103cf56ac4b3dcc4c48c5a184a933096",
            "Size": 4096, 
            "Annotations": null
        },
        {
            "MIMEType": "application/vnd.oci.image.layer.v1.tar",
            "Digest": "sha256:508be23c840e6e212e93d131cf85640a3b65810bd7037176ddad8070423f7cf3",
            "Size": 50742272,
            "Annotations": null
        }
    ],
    "Env": [
        "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "container=oci"
    ]
}
----

We will see that this container is based on the Red Hat UBI image. 

Let's look at the ubi9/ubi container that we built this off of and compare the layers section:

[{format_cmd}]
----
skopeo inspect containers-storage:registry.access.redhat.com/ubi9/ubi:latest
----

[{format_output}]
----
INFO[0000] Not using native diff for overlay, this may cause degraded performance for building images: 
kernel has CONFIG_OVERLAY_FS_REDIRECT_DIR enabled 
{        
    "Name": "registry.access.redhat.com/ubi10-beta/ubi",              
    "Digest": "sha256:4b4976d86eefeedab6884c9d2923206c6c3c2e2471206f97fd9d7aaaecbc04ac",        
    "RepoTags": [],     
    "Created": "2025-03-11T07:02:23.346219225Z",
    "DockerVersion": "",
    "Labels": {
        "architecture": "x86_64",
        "build-date": "2025-03-11T07:01:34",                                                           
        "com.redhat.component": "ubi10-container",
        "com.redhat.license_terms": "https://www.redhat.com/en/about/red-hat-end-user-license-agreement
s#UBI",
        "description": "The Universal Base Image is designed and engineered to be the base layer for al
l of your containerized applications, middleware and utilities. This base image is freely redistributab
le, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. This ima
ge is maintained by Red Hat and updated regularly.",
        "distribution-scope": "public",
        "io.buildah.version": "1.39.0-dev",
        "io.k8s.description": "The Universal Base Image is designed and engineered to be the base layer
 for all of your containerized applications, middleware and utilities. This base image is freely redist
ributable, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. T
his image is maintained by Red Hat and updated regularly.",
        "io.k8s.display-name": "Red Hat Universal Base Image 10",
        "io.openshift.expose-services": "",
        "io.openshift.tags": "base rhel10",
        "maintainer": "Red Hat, Inc.",
        "name": "ubi10",
        "release": "1741674993",
        "summary": "Provides the latest release of Red Hat Universal Base Image 10.",
        "url": "https://www.redhat.com",
        "vcs-ref": "eedd49665e8d30810907cf4ebb351ff15ebb8735",
        "vcs-type": "git",
        "vendor": "Red Hat, Inc.",
        "version": "10.0-beta"
    },
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:bd69bf9256bd9b0fbff30ca8f0b5267c2703b4e4355da451d72ffc475b5c7c7e",
        "sha256:9dcf0326ccda4b17d9579049f09549e93a71c986da6166d766529ce83aa57fff"
    ],
    "LayersData": [
        {
            "MIMEType": "application/vnd.oci.image.layer.v1.tar+gzip",
            "Digest": "sha256:bd69bf9256bd9b0fbff30ca8f0b5267c2703b4e4355da451d72ffc475b5c7c7e",
            "Size": 78479306,
            "Annotations": null
        },
        {
            "MIMEType": "application/vnd.oci.image.layer.v1.tar+gzip",
            "Digest": "sha256:9dcf0326ccda4b17d9579049f09549e93a71c986da6166d766529ce83aa57fff",
            "Size": 460,
            "Annotations": null
        }
    ],
    "Env": [
        "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "container=oci"
    ]
}
----

Comparing the layers section, we can see that our container has 3 layers whereas the original container only has 2 layers. In this, we can tell that there are differences between these containers.

Pretty neat that we can look inside local containers, but what about containers that are in registries? Skopeo can inspect containers on remote registries without the need to pull the image locally. Let's give that a test:

[{format_cmd}]
----
skopeo inspect docker://registry.access.redhat.com/ubi10-beta/ubi-minimal:latest
----

Again, there's a lot of information to inspect but just know that you are looking at data about an image that is not stored locally.

To confirm, let's list the local images and verify ubi-minimal is not among them.

[{format_cmd}]
----
podman images
----

[{format_output}]
----
REPOSITORY                                 TAG         IMAGE ID      CREATED        SIZE
localhost/webserver2                       latest      eb03c25f4be6  7 minutes ago  263 MB
registry.access.redhat.com/ubi9/ubi        latest      18ac20acd5ec  3 days ago     217 MB
registry.access.redhat.com/ubi10-beta/ubi  latest      8ba11fcef4ef  7 weeks ago    212 MB
----

Notice that ubi10-/ubi-minimal is not local to our registry. Skopeo provided that inspection completely remotely.

=== Obtaining tarballs of containers in remote registries for further inspection

Let's run:

[{format_cmd}]
----
mkdir /root/ubi-tarball
----

[{format_cmd}]
----
skopeo copy docker://registry.access.redhat.com/ubi10-beta/ubi-minimal:latest dir:/root/ubi-tarball
----

[{format_output}]
----
Getting image source signatures
Checking if image destination supports signatures
Copying blob c14a836c256b done   | 
Copying blob 3ae9a56dd415 done   | 
Copying config ead4841b04 done   | 
Writing manifest to image destination
Storing signatures
----

and now we can do:

[{format_cmd}]
----
cd /root/ubi-tarball
ls -l
----

[{format_output}]
----
total 37024
-rw-r--r--. 1 root root     6242 Sep 25 22:32 088f0967f6b5742f78966cbaa7012fd7f5091a9b9d547a5c31ddde64a9581595
-rw-r--r--. 1 root root 37869610 Sep 25 22:32 35e8d0567610305e5133f45eac553d3f57e4f33e2f764a1f16bab4f3bf24ad86
-rw-r--r--. 1 root root      429 Sep 25 22:32 manifest.json
-rw-r--r--. 1 root root      869 Sep 25 22:32 signature-1
-rw-r--r--. 1 root root      872 Sep 25 22:32 signature-2
-rw-r--r--. 1 root root      871 Sep 25 22:32 signature-3
-rw-r--r--. 1 root root      860 Sep 25 22:32 signature-4
-rw-r--r--. 1 root root      864 Sep 25 22:32 signature-5
-rw-r--r--. 1 root root      864 Sep 25 22:32 signature-6
-rw-r--r--. 1 root root       33 Sep 25 22:32 version
----

Inspecting the images with the `file` command, we discover that these a couple of text file along with a couple of zipped (compressed) tar files.

[{format_cmd}]
----
file *
----

[{format_output}]
----
3ae9a56dd415684c7b0131316b2900be82cab18b5a04964f74d3d204d63507cc: gzip compressed data, original size modulo 2^32 81126400
c14a836c256beab3872799b2695fddc3322dd51bff0a025ecfb721c0850a6892: gzip compressed data, original size modulo 2^32 4096
ead4841b0404dee891f30f94cf0c28351d13d1b7360cd87607437a973f47d347: JSON text data
manifest.json:                                                    JSON text data
signature-1:                                                      data
signature-2:                                                      data
signature-3:                                                      data
signature-4:                                                      data
signature-5:                                                      data
signature-6:                                                      data
signature-7:                                                      data
signature-8:                                                      data
version:                                                          ASCII text
----

Let's take a test view of the contents of the largest gzip file (examine "original size"):

[{format_cmd}]
----
tar ztvf $(ls --sort=size | head -1)
----

[{format_output}]
----
dr-xr-xr-x 0/0               0 2024-10-29 00:00 afs/
lrwxrwxrwx 0/0               0 2024-10-29 00:00 bin -> usr/bin
dr-xr-xr-x 0/0               0 2024-10-29 00:00 boot/
drwxr-sr-x 0/0               0 2025-03-11 09:26 cachi2/
drwxr-xr-x 0/0               0 2025-03-11 09:26 dev/
-rw-r--r-- 0/0               0 2025-03-11 09:26 dev/null
drwxr-xr-x 0/0               0 2025-03-11 09:26 etc/
-rw-r--r-- 0/0              94 2024-10-29 00:00 etc/GREP_COLORS
drwxr-xr-x 0/0               0 2025-03-11 09:26 etc/X11/
drwxr-xr-x 0/0               0 2024-10-29 00:00 etc/X11/applnk/
drwxr-xr-x 0/0               0 2024-10-29 00:00 etc/X11/fontpath.d/
drwxr-xr-x 0/0               0 2025-03-11 09:26 etc/X11/xinit/
drwxr-xr-x 0/0               0 2024-10-29 00:00 etc/X11/xinit/xinitrc.d/
drwxr-xr-x 0/0               0 2024-10-29 00:00 etc/X11/xinit/xinput.d/
-rw-r--r-- 0/0            1529 2023-11-29 10:34 etc/aliases

...<ouptut_truncated>...
----

The output is going to scroll by rather quickly, but just note that this is a complete filesystem for the container image.

NOTE: If you are more curious and would like to inspect the details a little further you could pipe the output to `more` or `less` and page through the archive contents.  `tar ztvf $(ls --sort=size | head -1) | less`

The other two numeric files provided in the image download are:

  * a copy of the metadata in text 
  * an additional tarball of any container secrets
  
Lastly, a couple of ASCII text files:

  * oci config info used to build the container
  * version info
  * manifest info

=== Other Uses of Skopeo

Skopeo can also do the following things:

  * Copy an image (manifest, filesystem layers, signatures) from one location to another. It can convert between manifest types in doing this (oci, v2s1, v2s2)
  * Delete images from registries that you have admin rights to.
  * Push images to registries that you have push rights to.

Examples of how to do these things are available in 'man skopeo'

=== Cleanup

[{format_cmd}]
----
podman stop --all
podman rm --all

buildah rm --all

podman rmi --all
buildah rmi --all
----

== Conclusion

This concludes the exercises related to buildah and skopeo.

Time to finish this unit and return the shell to it's home position.

[{format_cmd}]
----
workshop-finish-exercise.sh
----


[discrete]
== Additional Reference Materials

NOTE: You are not required to reference any additional resources for these exercises.  This is informational only.

    * link:https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image?sc_cid=701f2000000txokAAA&utm_source=bambu&utm_medium=social&utm_campaign=abm[Introducing the Red Hat Universal Base Image - Scott McCarty]
    * link:https://linuxhandbook.com/buildah-basics/[Getting Started with Buildah - Servesha]

[discrete]
== End of Unit

ifdef::env-github[]
link:../RHEL10-Workshop.adoc#toc[Return to TOC]
endif::[]

////
Always end files with a blank line to avoid include problems.
////

