
= *Container Management* (podman)

[discrete]
== *Skill Level: Intermediate*




== Overview

Podman (the POD manager) is a tool for developing, managing, and running containers on your Linux systems.

In this unit, we will get familiar with application containers and the podman CLI.  

== Getting Started

For these exercises, you will be using the host `node3` as user `root`.

From host `bastion`, ssh to `node3`.

[{format_cmd}]
----
ssh node3
----

Use `sudo` to elevate your privileges.

[{format_cmd}]
----
[[ "$UID" == 0 ]] || sudo -i
----

Verify that you are on the right host for these exercises.

[{format_cmd}]
----
workshop-podman-checkhost.sh
----

You are now ready to proceed with these exercises.

== Core Concepts


Linux containers are technologies (plural) that allow you to package and isolate applications as lightweight, portable entities. When compared to a traditional virtual machine (as containers often are), Linux containers:


  * improve resource utlitization over virtual machines
  * improve performance over virtual machines
  * improve flexibilty over virtual machines

Because container images include only the content needed to run an application, a container is more efficient 
requires less to run.  Likewise, since the container is not running the entirty of a complete operating system,
it will typically run faster than an application that carries with it the overhead of a whole new virtual 
machine.  Lastly with an application’s run time requirements included in the image itself, a container is 
far more capable of being run in multiple environments (without modification).

That said, let's begin to explore the capabilities of podman.

=== Essential Container Commands

Here is a list of the fundamental podman commands and their purpose:

  * *podman images* - list images
  * *podman ps* - lists running containers
  * *podman pull* - pulls (copies) container image from repository (ie: redhat and/or docker hub)
  * *podman run* - run a container
  * *podman inspect* - view facts about a container
  * *podman logs* - display logs of a container (can be used with --follow)
  * *podman rm* - remove one or more containers
  * *podman rmi* - remove one or more images
  * *podman stop* - stops one or more containers
  * *podman kill $(podman ps -q)* - kill all running containers
  * *podman rm $(podman ps -a -q)* - deletes all stopped containers

== Exercise: Basic Information

Now have a look at the general container information.

[{format_cmd}]
----
podman info
----

[{format_output}]
----
host:
  arch: amd64
  buildahVersion: 1.24.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
...<SNIP>...
----

There is obviously a lot of information here, but we are just trying to point out
how to get to that info when you need it.



== Exercise: Container Image Management

=== List Current Images

Now have a look at the general container information.

[{format_cmd}]
----
podman images
----

Your results should have come back empty and that's because we have not imported, loaded or pulled any containers on to our platform.  



=== Pull New Images

Time to pull a container from our local repository.

[{format_cmd}]
----
podman pull ubi9/ubi
----

[{format_output}]
----
Resolved "ubi9/ubi" as an alias (/etc/containers/registries.conf.d/001-rhel-shortnames.conf)
Trying to pull registry.access.redhat.com/ubi9/ubi:latest...
Getting image source signatures
Checking if image destination supports signatures
Copying blob 3b7adf049118 done
Copying config 9f43f297e7 done
Writing manifest to image destination
Storing signatures
9f43f297e77bc6937de12d4e90ed5dc679bd3b9c7a481068d2a840f5244d4197
----

Have a look at the image list now.

[{format_cmd}]
----
podman images
----

[{format_output}]
----
REPOSITORY                           TAG         IMAGE ID      CREATED      SIZE
registry.access.redhat.com/ubi9/ubi  latest      9f43f297e77b  2 weeks ago  217 MB
----

NOTE: if you are a subscriber to Red Hat Enterprise Linux, you can pull authentic Red Hat certified images directly from Red Hat's repository.  For example: `podman pull rhel7.5 --creds 'username:password'`

Pull a few more container images.

[{format_cmd}]
----
podman pull ubi9/ubi-minimal
podman pull ubi9/ubi-init
----

[{format_cmd}]
----
podman images
----

[{format_output}]
----
REPOSITORY                                   TAG         IMAGE ID      CREATED      SIZE
registry.access.redhat.com/ubi9/ubi-init     latest      a45c5d18b941  2 weeks ago  235 MB
registry.access.redhat.com/ubi9/ubi          latest      9f43f297e77b  2 weeks ago  217 MB
registry.access.redhat.com/ubi9/ubi-minimal  latest      088f0967f6b5  2 weeks ago  97.4 MB
----



=== Tag Images

Container images can also be tagged with convenient (ie:custom names).  This could make it more intuitive to understand what they 
contain, especially after an image has been customized.

[{format_cmd}]
----
podman tag registry.access.redhat.com/ubi9/ubi myfavorite
----

[{format_cmd}]
----
podman images
----

[{format_output}]
----
REPOSITORY                                   TAG         IMAGE ID      CREATED      SIZE
registry.access.redhat.com/ubi9/ubi-init     latest      a45c5d18b941  2 weeks ago  235 MB
registry.access.redhat.com/ubi9/ubi          latest      9f43f297e77b  2 weeks ago  217 MB
localhost/myfavorite                         latest      9f43f297e77b  2 weeks ago  217 MB
registry.access.redhat.com/ubi9/ubi-minimal  latest      088f0967f6b5  2 weeks ago  97.4 MB
----

Notice how the image-id for "ubi" and "myfavorite" are identical.

NOTE: The link:https://access.redhat.com/containers[Red Hat Container Catalog] (RHCC) provides a convenient service to locate certified container images built and supported by Red Hat.  You can also view the "security evaluation" for each image.



=== Delete Images

[{format_cmd}]
----
podman images
----

[{format_cmd}]
----
podman rmi ubi-init
----

[{format_cmd}]
----
podman images
----

[{format_output}]
----
REPOSITORY                                   TAG         IMAGE ID      CREATED      SIZE
registry.access.redhat.com/ubi9/ubi          latest      9f43f297e77b  2 weeks ago  217 MB
localhost/myfavorite                         latest      9f43f297e77b  2 weeks ago  217 MB
registry.access.redhat.com/ubi9/ubi-minimal  latest      088f0967f6b5  2 weeks ago  97.4 MB
----



== Exercise: Run a Container

=== Hello World

[{format_cmd}]
----
podman run ubi echo "hello world"
----

[{format_output}]
----
hello world
----

Well that was really boring!! What did we learn from this?  For starters, you should have noticed how fast the container launched and then concluded.  Compare that with traditional virtualization where:

    * you power up, 
    * wait for bios, 
    * wait for grub, 
    * wait for the kernel to boot and initialize resources,
    * pivot root, 
    * launch all the services, and then finally
    * run the application

Let us run a few more commands to see what else we can glean.

[{format_cmd}]
----
podman ps -a
----

[{format_output}]
----
CONTAINER ID  IMAGE                                       COMMAND           CREATED         STATUS                     PORTS       NAMES
fc07b3e29378  registry.access.redhat.com/ubi9/ubi:latest  echo hello world  35 seconds ago  Exited (0) 35 seconds ago              amazing_payne
----

Now let us run the exact same command as before to print "hello world".

[{format_cmd}]
----
podman run ubi echo "hello world"
----

[{format_output}]
----
hello world
----

Check out 'podman info' one more time and you should notice a few changes.

[{format_cmd}]
----
podman info
----

[{format_output}]
----
host:
  arch: amd64
  buildahVersion: 1.24.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
...<SNIP>...
----

Again, there is a lot of information here.  But if you dig into it, you should notice that 
the number of containers (ContainerStore) has incremented to 2, and that the number of 
ImageStore(s) has grown.  

=== Cleanup

Run 'podman ps -a' to the IDs of the exited containers.

[{format_cmd}]
----
podman ps -a
----

[{format_output}]
----
CONTAINER ID  IMAGE                                       COMMAND           CREATED             STATUS                         PORTS       NAMES
fc07b3e29378  registry.access.redhat.com/ubi9/ubi:latest  echo hello world  3 minutes ago       Exited (0) 3 minutes ago                   amazing_payne
eb8556004620  registry.access.redhat.com/ubi9/ubi:latest  echo hello world  About a minute ago  Exited (0) About a minute ago              peaceful_sutherland
----

Using the container UIDs from the above output, you could clean up the 'exited' containers individually using `podman rm <CONTAINER-ID> <CONTAINER-ID>`, 
but we are lazy and will cleanup up the containers with a single command:

[{format_cmd}]
----
podman rm --all
----

Now you should be able to run 'podman ps -a' again, and the results should come back empty.

[{format_cmd}]
----
podman ps -a
----


=== Conclusion

[{format_cmd}]
----
workshop-finish-exercise.sh
----



[discrete]
== Additional Reference Materials

    * link:https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image[Introducing the Red Hat Universal Base Image - Scott McCarty]
    * link:https://developers.redhat.com/blog/2019/04/25/podman-basics-workshop-sheet/[Podman Basics Cheat Sheet - Doug Tidwell]
    * link:https://developers.redhat.com/blog/2018/11/20/buildah-podman-containers-without-daemons/[Containers without daemons: Podman and Buildah available in RHEL 7.6 and RHEL 8 Beta - Tom Sweeney]

[discrete]
== End of Unit

////
Always end files with a blank line to avoid include problems.
////

