
= Intermediate: *Package Management* (dnf)

== Overview

You have already been introduced to *dnf* and the fundamentals of package management.  Now we'll progress to more sophisticated capability of *dnf* and management of the repositories that back the highlevel tools.

=== DNF

==== Aliases

==== Check

==== Query

dnf repoquery -l netstat

==== Search

dnf search netcat

==== Group

dnf grouplist

dnf groupinstall "RPM Development Tools"

==== Clean

dnf clean all

=== Repositories

DNF operates on the concept of package repositories, commonly referred to as repos.  

    * System can have a single or many repos configured

Repos typically fall into 2 categories:

    * Traditional - static pool of packages organized into structured filesystem for local or remote access

    * Managed / Service - service that provides dynamic managed repos (ex: Red Hat Satellite)

==== List Repos

==== Add Repo

==== Remove Repo

=== Modularity and App-Stream

Add blurb about Modularity and App Stream changes in RHEL 10

== Further Reading

    * link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/installing_managing_and_removing_user-space_components/index[RHEL 8 Documentation: Installing, Managing, and Removing User Space Components]
    * link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/installing_managing_and_removing_user-space_components/using-appstream_using-appstream[RHEL 8 Documentation: Using Appstream]
    
