
= *Firewall Management* (firewalld)

[discrete]
== *Skill Level: Intermediate*




== Overview

== Getting Started

For these exercises, you will be using the host `node1` as user `root`.

From host `bastion`, ssh to `node1`.

[{format_cmd_exec}]
----
ssh node1
----

Use `sudo` to elevate your privileges.

[{format_cmd_exec}]
----
[[ "$UID" == 0 ]] || sudo -i
----

Verify that you are on the right host for these exercises.

[{format_cmd_exec}]
----
workshop-firewalld-checkhost.sh
----

You are now ready to proceed with these exercises.



== Core Concepts


== Managing Ad-hoc Ports

=== Add a Port

Since we have been toying with http, it's common for httpd to also be configured on ports 8080 and 8443.  So let's simply create and ad-hoc rule to make those ports available.

[{format_cmd_exec}]
----
firewall-cmd --add-port=8080/tcp --add-port=8443/tcp
firewall-cmd --runtime-to-permanent
----

[{format_cmd_exec}]
----
firewall-cmd --zone=public --list-all
----

[{format_cmd_output}]
----
public
  target: default
  icmp-block-inversion: no
  interfaces:
  sources:
  services: cockpit http https ssh
  ports: 8080/tcp 8443/tcp
  protocols:
  forward: yes
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
----

=== Remove a Port

As much fun as that was, ad-hoc was quick and easy but not ideal.  We really desire a formal configuration, so let us undo the ad-hoc rules.

[{format_cmd_exec}]
----
firewall-cmd --remove-port=8080/tcp --remove-port=8443/tcp
firewall-cmd --runtime-to-permanent
----

[{format_cmd_exec}]
----
firewall-cmd --zone=public --list-all
----

[{format_cmd_output}]
----
public
  target: default
  icmp-block-inversion: no
  interfaces:
  sources:
  services: cockpit http https ssh
  ports:
  protocols:
  forward: yes
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
----



== Customizing a Default Service

=== Install Override Configuration 

[{format_cmd_exec}]
----
workshop-firewalld-customconfigs.sh
----

Two configuration files were just created */etc/firewalld/services*

They are identical to the system defaults except that our additional ports (8080 and 8443) were added the the definition.

[{format_cmd_exec}]
----
cat /etc/firewalld/services/http.xml
----

[{format_cmd_output}]
----
<?xml version="1.0" encoding="utf-8"?>
<service>
  <short>WWW (HTTP)</short>
  <description>HTTP is the protocol used to serve Web pages. If you plan to make your Web server publicly available, enable this option. This option is not required for viewing pages locally or developing Web pages.</description>
  <port protocol="tcp" port="80"/>
  <port protocol="tcp" port="8080"/>
</service>
----

[{format_cmd_exec}]
----
cat /etc/firewalld/services/https.xml
----

[{format_cmd_output}]
----
<?xml version="1.0" encoding="utf-8"?>
<service>
  <short>Secure WWW (HTTPS)</short>
  <description>HTTPS is a modified HTTP used to serve Web pages when security is important. Examples are sites that require logins like stores or web mail. This option is not required for viewing pages locally or developing Web pages. You need the httpd package installed for this option to be useful.</description>
  <port protocol="tcp" port="443"/>
  <port protocol="tcp" port="8443"/>
</service>
----

===  Activate Service

Since the httpd service is already active, all we really need to do is reload firewalld.

[{format_cmd_exec}]
----
firewall-cmd --reload
----

=== Verification

[{format_cmd_exec}]
----
firewall-cmd --info-service=http
----

[{format_cmd_output}]
----
http
  ports: 80/tcp 8080/tcp
  protocols:
  source-ports:
  modules:
  destination:
  includes:
  helpers:
----

[{format_cmd_exec}]
----
firewall-cmd --info-service=https
----

[{format_cmd_output}]
----
https
  ports: 443/tcp 8443/tcp
  protocols:
  source-ports:
  modules:
  destination:
  includes:
  helpers:
----

[{format_cmd_exec}]
----
firewall-cmd --zone=public --list-all --permanent
----

[{format_cmd_output}]
----
public
  target: default
  icmp-block-inversion: no
  interfaces:
  sources:
  services: cockpit http https ssh
  ports: 
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
----



== Custom Service From Scratch

In this exercise you will create a custom service with a unique name.

=== Configuration File

First, have a look at the configuration file which has already been prepared for you.  It should be fairly self explanatory.

[{format_cmd_exec}]
----
cat /usr/local/etc/firewalld-customname.xml
----

./usr/local/etc/firewalld-customname.xml
[{format_cmd_output}]
----
<?xml version="1.0" encoding="utf-8"?>
<service>
 <short>workshop</short>
 <description>Workshop Test Service</description>
 <port protocol="tcp" port="7890" />
 <port protocol="udp" port="7890" />
</service>
----

=== Configuration Import

Now it is time to import the config file.

[{format_cmd_exec}]
----
firewall-cmd --new-service-from-file=/usr/local/etc/firewalld-customname.xml --name=workshop --permanent
----

[{format_cmd_exec}]
----
firewall-cmd --reload
----

=== Activate Service

Finally, activate the service and verify.

[{format_cmd_exec}]
----
firewall-cmd --add-service=workshop
----

[{format_cmd_exec}]
----
firewall-cmd --zone=public --list-all
----


Just make note of the fact we did not use the '--permanent' option with any of our commands.  If the system reboots, or if firewalld is reloaded then the custom named serviced will be lost.  You can preserve the customizations with a simple `firewall-cmd --runtime-to-permanent`

And you are done!

== Panic Mode

Panic mode allows you to immediately turn off all network traffic on a host.  

This is handy to know, but unless you are on the physical system console or remote managed console (ie: ILO, DRAC, etc...) this can be very disruptive.  So we'll provide the commands under the strict guidance that you *DON'T RUN THESE COMMANDS* during this workshop.

[WARNING]
====
_DO NOT RUN THESE COMMANDS_
----
firewall-cmd --query-panic

firewall-cmd --panic-on 

firewall-cmd --panic-off
----
====

== Conclusion

That concludes this unit on firewalld. 

Time to finish this unit and return the shell to it's home position.

[{format_cmd_exec}]
----
workshop-finish-exercise.sh
----

== Additional Resources

You can find more information:

    * link:https://developers.redhat.com/blog/2018/08/10/firewalld-the-future-is-nftables/[Firewalld: The Future is nftables]
    * link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/configuring_firewalls_and_packet_filters/using-and-configuring-firewalld_firewall-packet-filters[Using And Configuring Firewalls]
    
[discrete]
== End of Unit

ifdef::env-github[]
link:../RHEL10-Workshop.adoc#toc[Return to TOC]
endif::[]

////
Always end files with a blank line to avoid include problems.
////

