
= *Help* (LightSpeed)

[discrete]
== *Skill Level: Intermediate*




== Overview

Red Hat Enterprise Linux Lightspeed will offer intelligent, natural language processing capabilities, intended to make OpenShift and RHEL easier for novices to use and more efficient for experienced professionals.

== Getting Started

For these exercises, you will be using the host `node3` as user `root`.

From host `bastion`, ssh to `node3`.

[{format_cmd}]
----
ssh node3
----

Use `sudo` to elevate your privileges.

[{format_cmd}]
----
[[ "$UID" == 0 ]] || sudo -i
----

Verify that you are on the right host for these exercises.

[{format_cmd}]
----
workshop-systemd-checkhost.sh
----

You are now ready to proceed with these exercises.

== Core Concepts

The Command Line Assistant (CLA) powered by RHEL Lightspeed is a generative AI assistant designed to assist new and experienced users  when they interact with RHEL through the command line. CLA can help with several tasks such as: answering RHEL related questions, assisting with troubleshooting, assisting with deciphering log entries, and many others. CLA provides a natural language interface, and can incorporate information from sources such as the RHEL documentation, knowledge base articles, reference architectures and more resources. It is a powerful tool that enables admins to more easily manage, troubleshoot, and work with RHEL systems.



== Getting Started with CLA



== Do something else



== Do soething sensational




ifdef::env-github[]
link:../RHEL10-Workshop.adoc#toc[Return to TOC]
endif::[]

////
Always end files with a blank line to avoid include problems.
////

