
= *Help* (LightSpeed)

[discrete]
== *Skill Level: Intermediate*




== Overview

Red Hat Enterprise Linux Lightspeed will offer intelligent, natural language processing capabilities, intended to make OpenShift and RHEL easier for novices to use and more efficient for experienced professionals.

== Getting Started

For these exercises, you will be using the host `node3` as user `root`.

From host `bastion`, ssh to `node3`.

[{format_cmd}]
----
ssh node3
----

Use `sudo` to elevate your privileges.

[{format_cmd}]
----
[[ "$UID" == 0 ]] || sudo -i
----

Verify that you are on the right host for these exercises.

[{format_cmd}]
----
workshop-systemd-checkhost.sh
----

You are now ready to proceed with these exercises.

== Core Concepts

This exercise will expand on the basics of RHEL Lightspeed by introducing additional capabilities beyond just asking questions.  These include:

  * piping command output to the command line assistant
  * attaching a file to the command line assistant


== Start the Apache Web Server - Maybe?

Let's begin by issuing the command to start the Apache web server

[{format_cmd}]
----
systemctl start httpd
----

The web service didn't start properly, and instead gave us an error message and a couple of commands to run to get possible further information.

[{format_output}]
----
Job for httpd.service failed because the control process exited with error code.
See "systemctl status httpd.service" and "journalctl -xeu httpd.service" for details.
----


== Do something else



== Do soething sensational




ifdef::env-github[]
link:../RHEL10-Workshop.adoc#toc[Return to TOC]
endif::[]

////
Always end files with a blank line to avoid include problems.
////

