
= *Package Management* (dnf)

[discrete]
== *Skill Level: Intermediate*




== Overview

You have already been introduced to *dnf* and the fundamentals of package management.  Now we'll progress to the more sophisticated capabilities of *dnf* and management of the repositories that back the highlevel tools.


== More About dnf

=== Search

Not every tool is delvered in it's own unique rpm package.  Tools are often bundled into collective packages under a common name (category).  
For example, let's try to running the utility command called *netstat*.

[{format_cmd}]
----
netstat -tulpn
----

[{format_cmd_output}]
----
-bash: netstat: command not found
----

As you can tell, the netstat utility is missing from our platform.
If you try to install the netstat package, you'll discover that no such package exists.

So in order to track down which package contains our specified tool, we use the *provides* subcommand.

[{format_cmd}]
----
dnf provides netstat
----

[{format_cmd_output}]
----
net-tools-2.0-0.72.20160912git.el10.x86_64 : Basic networking tools
Repo        : rhel-10-for-x86_64-baseos-beta-rpms
Matched from:
Filename    : /usr/bin/netstat

net-tools-2.0-0.73.20160912git.el10.x86_64 : Basic networking tools
Repo        : rhel-10-for-x86_64-baseos-beta-rpms
Matched from:
Filename    : /usr/bin/netstat
----

From this we can determine that a package called 'net-tools' provides the requested utility.
So let us proceed to install it.

[{format_cmd}]
----
dnf install -y net-tools
----

[{format_cmd}]
----
netstat -tulpn
----



=== Repo Query & Dependencies

Packages often (ie: the majority of the time) have dependencies on other additional packages which are required for a successful installation.  Resolving those dependencies is one of the core fuctions of dnf. 

In order to explore dependencies, we will use a nice little subcommand called *repoquery* which is equivalent to 'rpm -q'.  With the added flag *--requires* you
can quickly determine what additional packages are needed by a specified package.

Let us begin by getting information about a package called 'ncurses'

[{format_cmd}]
----
dnf info ncurses
----

What other packages does this depend on.

[{format_cmd}]
----
dnf repoquery --depends ncurses
----

How about the other way around, what other packages have a dependency on *ncurses*.

[{format_cmd}]
----
dnf repoquery --whatdepends ncurses
----

From this ouptut you can determine what other tools are impacted if you were to attempt a *dnf remove* or *dnf update* of ncurses.




=== Aliases

Aliases allow the user to abbreviate longer command sequences with short names (in the form <name=value>).

For example, if you're tired of typing all the characters in *dnf list* and preferred *dnf ls* then you would create an alias like this.

[{format_cmd}]
----
dnf alias add ls=list
----

[{format_cmd}]
----
dnf ls
----

Well that's kind of interesting but a pretty lame example.  The real value comes when adding options to the command which vary from the defaults.

Let's create an alias *li* to use as a substitute for *list --installed* but we'll use a repoquery to change the output format.

[{format_cmd_noattr}]
----
dnf alias add li='repoquery --installed --qf %{installtime}\t%{vendor}\t%{arch}\t%{name}-%{version}'
----

[{format_cmd}]
----
dnf li
----

Or, how about an alias for listing the available packages

[{format_cmd_noattr}]
----
dnf alias add la='repoquery --available --qf %{reponame}\t%{arch}\t%{name}-%{version}'
----

[{format_cmd}]
----
dnf la
----

Here is how you see the list of the configured aliases.

[{format_cmd}]
----
dnf alias list 
----

And lastly, how to delete an alias.


[{format_cmd}]
----
dnf alias delete la
----




=== Groups

Package groups are definded in the repository.  Red Hat creates a few package groups in the distribution ISOs
inoder to make installations a little more covenient and consistent.

To see a list of available group names

[{format_cmd}]
----
dnf grouplist
----

To install a group you use the *groupinstall* command.  Since we are not interested in installing
anything for this workshop, we'll use the test flags that were introduced in the fundamentals unit.

[{format_cmd}]
----
dnf groupinstall "RPM Development Tools" -y --setopt tsflags=test
----

You could just as easily use the groupremove to uninstall the package collection.




=== Clean

After a session of installing and/or upgrading pacakges, there can be quite a bit of left over data
using up your precious storage.  To clean up the space, use the sub command 'clean'.

[{format_cmd}]
----
dnf clean all
----

== Repositories

DNF operates on the concept of package repositories, commonly referred to as repos.  

    * System can have a single or many repos configured

Repos typically fall into 2 categories:

    * Traditional - static pool of packages organized into structured filesystem for local or remote access

    * Managed / Service - service that provides dynamic managed repos (ex: Red Hat Satellite)

=== List Repos

[{format_cmd}]
----
dnf repolist
----

=== Add Repo

Repo configuration files are stored in '/etc/yum.repo.d'

Creating a repo config can be done:

   * by hand, 
   * by using the *dnf config-manager*, or 
   * by installing a package that contains the repo config (most common).  

Installing a package with the repo config often has the added advantage of installing keys which validate sources and improve security of your host.

A common repo to add to RHEL development systems is EPEL.  This repository (Extra Pacakges for Enterprise Linux) contains pacakges
from the Fedora development community which have been compiled and verified for installation on RHEL.  Software from EPEL offers a path
to trying new things on RHEL9 which not otherwise be possible.

NOTE:  The packages from EPEL are COMMUNITY SUPPORT ONLY!!!  We are using EPEL for example purposes only.

Let's add the EPEL repo for RHEL 10 to our host.

[{format_cmd}]
----
dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-10.noarch.rpm
----

[{format_cmd}]
----
dnf repolist
----

[{format_cmd_output}]
----
Updating Subscription Management repositories.
repo id                                  repo name
epel                                     Extra Packages for Enterprise Linux 10 - x86_64
rhel-10-for-x86_64-appstream-beta-rpms   Red Hat Enterprise Linux 10 for x86_64 - AppStream Beta (RPMs)
rhel-10-for-x86_64-baseos-beta-rpms      Red Hat Enterprise Linux 10 for x86_64 - BaseOS Beta (RPMs)
----

Now let's list all of the repos provided with configuration we just installed.  Notice how most of the
repos are disabled.  Should you need to install something from epel-testing repo, you could temporarily 
enable a repo by adding the --enable-repo=<name> flag to most dnf operations.

[{format_cmd_output}]
----
dnf repolist --all 'epel*'
----

[{format_cmd_output}]
----
Updating Subscription Management repositories.
repo id                   repo name                                                              status
epel                      Extra Packages for Enterprise Linux 10 - x86_64                        enabled
epel-debuginfo            Extra Packages for Enterprise Linux 10 - x86_64 - Debug                disabled
epel-source               Extra Packages for Enterprise Linux 10 - x86_64 - Source               disabled
epel-testing              Extra Packages for Enterprise Linux 10 - Testing - x86_64              disabled
epel-testing-debuginfo    Extra Packages for Enterprise Linux 10 - Testing - x86_64 - Debug      disabled
epel-testing-source       Extra Packages for Enterprise Linux 10 - Testing - x86_64 - Source     disabled
----

[{format_cmd_output}]
----
dnf repolist --all 'epel*' --enablerepo=epel-testing
----

[{format_cmd_output}]
----
Updating Subscription Management repositories.
repo id                   repo name                                                              status
epel                      Extra Packages for Enterprise Linux 10 - x86_64                        enabled
epel-debuginfo            Extra Packages for Enterprise Linux 10 - x86_64 - Debug                disabled
epel-source               Extra Packages for Enterprise Linux 10 - x86_64 - Source               disabled
epel-testing              Extra Packages for Enterprise Linux 10 - Testing - x86_64              enabled
epel-testing-debuginfo    Extra Packages for Enterprise Linux 10 - Testing - x86_64 - Debug      disabled
epel-testing-source       Extra Packages for Enterprise Linux 10 - Testing - x86_64 - Source     disabled
----

List the available pacakges from the EPEL repo

[{format_cmd_output}]
----
dnf list --available --repo epel
----




=== Disable Repo

Just like you can enable a repo temporarily, you can disable a repo temporarily as well.

[{format_cmd_output}]
----
dnf repolist --all 'epel*' --disablerepo=epel
----

For something more permanent, you can use config-manage to set the repo disabled.

[{format_cmd_output}]
----
dnf config-manager --set-disabled epel
----

[{format_cmd_output}]
----
dnf repolist --all 'epel*' 
----

Or you could edit the config file manually to flip the enabled flag.



=== Remove Repo

Removing a repo is a pretty simple operation which can be done in a couple of ways:

  * remove (or rename) the config file in /etc/yum.repos.d
  * use dnf to remove the pkg which added the repo config




=== Modularity and App-Stream

Add blurb about Modularity and App Stream changes in RHEL 10




== Further Reading

    * link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/installing_managing_and_removing_user-space_components/index[RHEL 8 Documentation: Installing, Managing, and Removing User Space Components]
    * link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/installing_managing_and_removing_user-space_components/using-appstream_using-appstream[RHEL 8 Documentation: Using Appstream]
    
