
= *Help* (LightSpeed)

[discrete]
== *Skill Level: Intermediate*




== Overview

Red Hat Enterprise Linux Lightspeed will offer intelligent, natural language processing capabilities, intended to make OpenShift and RHEL easier for novices to use and more efficient for experienced professionals.

== Getting Started

For these exercises, you will be using the host `node3` as user `root`.

From host `bastion`, ssh to `node3`.

[{format_cmd}]
----
ssh node3
----

Use `sudo` to elevate your privileges.

[{format_cmd}]
----
[[ "$UID" == 0 ]] || sudo -i
----

Verify that you are on the right host for these exercises.

[{format_cmd}]
----
workshop-systemd-checkhost.sh
----

You are now ready to proceed with these exercises.

== Core Concepts

This exercise will expand on the basics of RHEL Lightspeed by introducing additional capabilities beyond just asking questions.  These include:

  * piping command output to the command line assistant
  * attaching a file to the command line assistant


== Start the Apache Web Server - Maybe?

Let's begin by issuing the command to start the Apache web server

[{format_cmd}]
----
systemctl start httpd
----

The web service didn't start properly, and instead gave us an error message and a couple of commands to run to get possible further information.

[{format_output}]
----
Job for httpd.service failed because the control process exited with error code.
See "systemctl status httpd.service" and "journalctl -xeu httpd.service" for details.
----


== Have RHEL Lightspeed help figure out the issue

Running either or both of the commands will point to the error, but especially for those not very familiar with systemd and/or journalctl, the output can be a little confusing to read.  Let's see if the CLA can make it easier.

[{format_cmd}]
----
journalctl -xeu httpd.service | c "help find why httpd failed to start"
----

[{format_output}]
----

----




== Apache is up and running!  Now let's add web developer accounts



== Conclusion

That concludes this unit on the Command Line Assistant for RHEL Lightspeed.  You can find more info in the official Red Hat Command Line Assistant documentation or the man page (use "man c" ).  


Time to finish this unit and return the shell to it's home position.

[{format_cmd}]
----
workshop-finish-exercise.sh
----

== Additional Resources

You can find more information:

    * <<placeholder for CLA doc>>


ifdef::env-github[]
link:../RHEL10-Workshop.adoc#toc[Return to TOC]
endif::[]

[discrete]
== End of Unit

////
Always end files with a blank line to avoid include problems.
////

